language: java
sudo: required

jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx

env:
 global:
  - TSK_HOME=$TRAVIS_BUILD_DIR/sleuthkit/sleuthkit

addons:
  apt:
    update: true
    packages:
    - testdisk
    - libafflib-dev
    - libewf-dev
    - libpq-dev
    - autopoint
    - libsqlite3-dev
    - ant
    - ant-optional
    - libcppunit-dev
    - wget
    - openjdk-8-jdk
    - openjfx=8u161-b12-1ubuntu2
    - libopenjfx-java=8u161-b12-1ubuntu2
    - libopenjfx-jni=8u161-b12-1ubuntu2
  homebrew:
    update: true
    packages:
    - ant
    - wget
    - libpq
    - libewf
    - gettext
    - cppunit
    - afflib
    - testdisk

python:
  - "2.7"

before_install:
 - git clone https://github.com/sleuthkit/sleuthkit.git sleuthkit/sleuthkit
 - python setupSleuthkitBranch.py

install:
 - pushd sleuthkit/sleuthkit && ./travis_install_libs.sh && popd

before_script:
  - if [ $TRAVIS_OS_NAME = linux ]; then 
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java;
        sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac;
        export PATH=/usr/bin:$PATH; 
        unset JAVA_HOME;
    fi
  - if [ $TRAVIS_OS_NAME = osx ]; then
        brew uninstall java --force;
        brew cask uninstall java --force;
        brew tap homebrew/cask-versions;
        brew cask install corretto8;
        export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home;
    fi
  - java -version

script: ./travis_build.sh
